#!/bin/bash
# art.sh — cover fetch + color extraction only
# Wallpaper is generated by widget.py so there's no conflict

mkdir -p "$HOME/music-mode/cache"
[ ! -f "$HOME/music-mode/cache/current_cover.txt" ] && \
  echo "" > "$HOME/music-mode/cache/current_cover.txt"

LAST_URL=""
PLAYER_ARG="--player=spotify,%any"

while true; do
  STATUS=$(playerctl $PLAYER_ARG status 2>/dev/null)
  [ "$STATUS" != "Playing" ] && [ "$STATUS" != "Paused" ] && { sleep 1; continue; }

  RAW_URL=$(playerctl $PLAYER_ARG metadata mpris:artUrl 2>/dev/null)
  [ -z "$RAW_URL" ] && { sleep 1; continue; }

  CLEAN_URL=$(echo "$RAW_URL" | sed 's/\?.*//')
  [ "$CLEAN_URL" = "$LAST_URL" ] && { sleep 1; continue; }

  LAST_URL="$CLEAN_URL"
  echo "[art] fetching $CLEAN_URL"

  RAW="$HOME/music-mode/cache/cover_raw.jpg"
  TMP_DOWNLOAD="$HOME/music-mode/cache/cover_download.tmp"
  
  if [[ "$CLEAN_URL" == file://* ]]; then
    # Local file path
    LOCAL_PATH="${CLEAN_URL#file://}"
    # URL decode local path
    LOCAL_PATH="$(printf '%b' "${LOCAL_PATH//%/\\x}")"
    cp "$LOCAL_PATH" "$TMP_DOWNLOAD" 2>/dev/null
  else
    # Remote HTTP(S) path
    curl -sL "$CLEAN_URL" -o "$TMP_DOWNLOAD"
  fi

  if [ $? -eq 0 ] && [ -s "$TMP_DOWNLOAD" ]; then
    # Verify it's a valid image before replacing
    if file "$TMP_DOWNLOAD" 2>/dev/null | grep -qi "image"; then
      mv "$TMP_DOWNLOAD" "$RAW"
    else
      echo "[art] file is not a valid image — skipping"
      rm -f "$TMP_DOWNLOAD"
      sleep 1
      continue
    fi

    TS=$(date +%s)
    COVER="$HOME/music-mode/cache/cover_${TS}.jpg"
    COVER_TMP="$HOME/music-mode/cache/cover_${TS}.tmp.jpg"

    # Convert to tmp file first
    convert "$RAW" -resize 300x300 "$COVER_TMP" 2>/dev/null

    if [ $? -eq 0 ] && [ -s "$COVER_TMP" ]; then
      # Only now move into place and clean up old covers
      rm -f "$HOME/music-mode/cache/cover_"[0-9]*.jpg 2>/dev/null
      mv "$COVER_TMP" "$COVER"

      # Atomic write — widget reads this to find the cover path
      echo "$COVER" > "$HOME/music-mode/cache/current_cover.txt.tmp"
      mv "$HOME/music-mode/cache/current_cover.txt.tmp" \
         "$HOME/music-mode/cache/current_cover.txt"
      echo "[art] cover ready: $COVER"
    else
      echo "[art] convert failed"
      rm -f "$COVER_TMP"
    fi
  else
    echo "[art] download/copy failed"
    rm -f "$TMP_DOWNLOAD"
  fi

  sleep 1
done
