#!/bin/bash
# ── reload-colors.sh ──────────────────────────────────────────────────────────
# Reads the accent color written by the Music Mode widget, then rewrites
# ~/.config/i3/colors.conf and ~/.config/rofi/theme.rasi so i3 borders and
# the rofi launcher both match the current album art.
#
# Called automatically by ArtProcessor in widget.py after every new cover.
# Can also be run manually: bash ~/music-mode/scripts/reload-colors.sh

CACHE="$HOME/music-mode/cache"
ACCENT_FILE="$CACHE/color_accent.txt"
BRIGHT_FILE="$CACHE/color_brightness.txt"

I3_COLORS="$HOME/.config/i3/colors.conf"
ROFI_THEME="$HOME/.config/rofi/theme.rasi"

# ── Read accent color ─────────────────────────────────────────────────────────
ACCENT=$(cat "$ACCENT_FILE" 2>/dev/null | tr -d '[:space:]')
BRIGHT=$(cat "$BRIGHT_FILE" 2>/dev/null | tr -d '[:space:]')

# Validate — must be #rrggbb
if [[ ! "$ACCENT" =~ ^#[0-9a-fA-F]{6}$ ]]; then
    echo "[reload-colors] invalid accent '$ACCENT' — skipping"
    exit 0
fi

echo "[reload-colors] accent=$ACCENT bright=$BRIGHT"

# ── Derive palette from accent ────────────────────────────────────────────────
# Light theme: white background, dark text, accent for highlights.
# We generate a dimmed version of the accent for inactive borders.

python3 - "$ACCENT" "$BRIGHT" << 'PYEOF'
import sys, os

def hex_to_rgb(h):
    h = h.lstrip('#')
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))

def rgb_to_hex(r, g, b):
    return f"#{int(r):02x}{int(g):02x}{int(b):02x}"

def blend(c, target, t):
    return tuple(c[i] + (target[i] - c[i]) * t for i in range(3))

def clamp(v): return max(0, min(255, int(v)))

accent_hex = sys.argv[1]
bright      = int(sys.argv[2]) if len(sys.argv) > 2 and sys.argv[2].isdigit() else 128

ar, ag, ab = hex_to_rgb(accent_hex)

# Dim accent: blend toward white by 40%
white   = (255, 255, 255)
dim_rgb = blend((ar, ag, ab), white, 0.40)
accent_dim = rgb_to_hex(*[clamp(v) for v in dim_rgb])

# Very light tint of accent for hover backgrounds
tint_rgb = blend((ar, ag, ab), white, 0.82)
accent_tint = rgb_to_hex(*[clamp(v) for v in tint_rgb])

# Write i3 colors.conf
i3_path = os.path.expanduser("~/.config/i3/colors.conf")
os.makedirs(os.path.dirname(i3_path), exist_ok=True)
with open(i3_path, "w") as f:
    f.write(f"""# colors.conf — auto-generated by reload-colors.sh
# Do not edit — overwritten on every track change.

set $accent   {accent_hex}
set $bg       #ffffff
set $bg2      #f2f4f8
set $fg       #1a1a2e
set $fg2      #666688
set $border   #d8dde8
set $urgent   #ff4444

client.focused          {accent_hex}   #ffffff  #1a1a2e  {accent_hex}   {accent_hex}
client.focused_inactive #d8dde8   #f2f4f8  #666688  #d8dde8   #d8dde8
client.unfocused        #e8edf5   #ffffff  #888899  #e8edf5   #e8edf5
client.urgent           #ff4444   #fff0f0  #cc0000  #ff4444   #ff4444
""")
print(f"  i3 colors.conf → {accent_hex}")

# Write rofi theme.rasi
rofi_path = os.path.expanduser("~/.config/rofi/theme.rasi")
os.makedirs(os.path.dirname(rofi_path), exist_ok=True)
with open(rofi_path, "w") as f:
    f.write(f"""/* theme.rasi — auto-generated by reload-colors.sh */
* {{
    accent:      {accent_hex};
    accent-dim:  {accent_dim};
    bg:          #ffffff;
    bg2:         #f2f4f8;
    bg-hover:    {accent_tint};
    fg:          #1a1a2e;
    fg2:         #666688;
    border-col:  #d8dde8;
    radius:      8px;

    background-color: transparent;
    text-color:       @fg;
    border:           0;
    margin:           0;
    padding:          0;
    spacing:          0;
}}

window {{
    background-color: @bg;
    border:           2px solid;
    border-color:     @accent;
    border-radius:    @radius;
    width:            480px;
    padding:          0;
}}

mainbox {{
    background-color: transparent;
    children:         [ inputbar, listview ];
    padding:          0;
}}

inputbar {{
    background-color: @bg;
    border-radius:    @radius @radius 0 0;
    border:           0 0 1px 0;
    border-color:     @border-col;
    padding:          12px 16px;
    spacing:          10px;
    children:         [ prompt, entry ];
}}

prompt {{
    background-color: @accent;
    text-color:       @bg;
    border-radius:    4px;
    padding:          2px 8px;
    font:             "Inter SemiBold 11";
}}

entry {{
    background-color: transparent;
    text-color:       @fg;
    placeholder:      "Search…";
    placeholder-color: @fg2;
    cursor:           text;
    font:             "Inter 12";
}}

listview {{
    background-color: transparent;
    padding:          6px 8px;
    spacing:          2px;
    lines:            8;
    columns:          1;
    fixed-height:     true;
    scrollbar:        false;
}}

element {{
    background-color: transparent;
    border-radius:    6px;
    padding:          8px 10px;
    spacing:          10px;
    children:         [ element-icon, element-text ];
    orientation:      horizontal;
}}

element normal.normal,
element alternate.normal {{
    background-color: transparent;
    text-color:       @fg;
}}

element selected.normal {{
    background-color: @bg-hover;
    text-color:       @fg;
    border:           0 0 0 3px;
    border-color:     @accent;
}}

element normal.urgent,
element alternate.urgent {{
    text-color: #cc0000;
}}

element selected.urgent {{
    background-color: #fff0f0;
    text-color:       #cc0000;
}}

element-icon {{
    size:           22px;
    vertical-align: 0.5;
}}

element-text {{
    background-color: transparent;
    text-color:       inherit;
    vertical-align:   0.5;
    font:             "Inter 12";
}}

message {{
    background-color: @bg2;
    border-radius:    0 0 @radius @radius;
    padding:          8px 16px;
}}

textbox {{
    text-color: @fg2;
    font:       "Inter 11";
}}
""")
print(f"  rofi theme.rasi → {accent_hex} / dim={accent_dim} / tint={accent_tint}")
PYEOF

# ── Reload i3 borders live ────────────────────────────────────────────────────
# `i3-msg reload` re-reads colors.conf without restarting i3.
if command -v i3-msg &>/dev/null && i3-msg -t get_version &>/dev/null 2>&1; then
    i3-msg reload > /dev/null 2>&1
    echo "[reload-colors] i3 reloaded"
fi

echo "[reload-colors] done"
